# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image:
    name: floriaan1/plot-misc:master 
    entrypoint: ["/bin/sh", "-c"]
    # entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

stages:
  - check
  - test
  - deploy


# https://stackoverflow.com/questions/54074433/gitlab-ci-specifying-stages-in-before-script
.before_script_template: &build_test-integration
  before_script:
    # - resources/ci_cd/set_ssh_key.sh
    - resources/ci_cd/before_script.sh

pages:
  stage: deploy
  <<: *build_test-integration
  script:
    - resources/ci_cd/pages.sh
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sast:
  stage: test
  image: $CI_REGISTRY_IMAGE/codequality:latest 
  script:
    - analyze
  allow_failure: true
  artifacts:
    reports:
      sast: gl-sast-report.json
